backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/images/uploads
public_folder: /images/uploads
editor:
  preview: false

collections:
  - name: 'project'
    label: 'Project'
    folder: 'src/pages/projects'
    create: true
    slug: '{{year}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sub Title', name: 'subTitle', widget: 'string' }
      - { label: 'Course', name: 'course', required: false, widget: 'string' }
      - {
          label: 'Creators',
          name: 'creators',
          required: false,
          widget: 'string',
        }
      - { label: 'Created year', name: 'year', widget: 'number', default: 2018 }
      - {
          label: 'Year Level',
          name: 'yearLevel',
          widget: 'string',
          default: 'First',
          options: ['First', 'Second', 'Third'],
        }
      - { label: 'Description', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          default: /images/uploads/blank_project.jpg,
        }
      - {
          label: Contributions,
          name: contributions,
          widget: list,
          required: false,
          fields:
            [
              { label: Title, name: title, widget: string },
              {
                label: Creators,
                name: creators,
                required: false,
                widget: list,
              },
              { label: Description, name: description, widget: 'markdown' },
            ],
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/students/index.md'
        label: 'Students'
        name: 'students'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
